### ISSUE TITLE
[BUG] Cannot re-use chart objects in release 2.0 anymore

### ISSUE THREAD

**Issue by schroederjoa** [louisnw01/lightweight-charts-python#392]
### Expected Behavior

My goal is to create screenshots of multiple charts by using the same chart object in a loop. Inside the loop, the chart is first cleaned from data/lines and then populated again. This avoids the time consuming re-creation of the chart window. 

### Current Behaviour

Where this worked fine in version 1.0.22, it is now throwing following error in version 2.0:
0
done 0
1
Exception in thread Thread-2 (loop):
Traceback (most recent call last):
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\lightweight_charts\chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\webview\window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\webview\window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'TypeError', 'stack': "TypeError: Cannot read properties of undefined (reading 'forEach')\n    at eval (eval at <anonymous> (:4:29), <anonymous>:3:42)\n    at <anonymous>:4:29", 'message': "Cannot read properties of undefined (reading 'forEach')"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joach\anaconda3\envs\py310n\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\joach\anaconda3\envs\py310n\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
KeyError: 'line'

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

import talib   

if __name__ == '__main__':

	df = pd.read_csv('ohlcv.csv')
	#df2 = pd.read_csv('rsi.csv')
	
	df2 = pd.DataFrame({'time':df.date, 'value':talib.RSI(df.close, timeperiod=14)})
	
	chart = Chart(inner_width=1, inner_height=0.8)
	chart.time_scale(visible=False)
	chart2 = chart.create_subchart(width=1, height=0.2, sync=True)

	for i in range(10):
	
		[l.delete() for l in chart.lines()]
		[l.delete() for l in chart2.lines()]
		chart.set(None)
		chart2.set(None)
	
		print(i)
		chart.set(df)
		chart.show()
	
		line = chart2.create_line()
		line.set(df2)
	
		chart.fit()

		images = [chart.screenshot(), chart2.screenshot()]
		print("done",i)

	chart.exit()
```

### Environment

```markdown
- OS: Windows 11
- Library: 2.0
```

**Comment by louisnw01** [comment]
Fixed in 2.0.1 @schroederjoa

**Comment by schroederjoa** [comment]
Hi @louisnw01, thanks a lot. The reproducible example is working now, but in my program (that works with 1.0.22) I am still getting the following error. Can you use that error msg or do you want me to try and prepare another reproducible example?

Exception in thread Thread-2 (loop):
Traceback (most recent call last):
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\lightweight_charts\chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\webview\window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\webview\window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'Error', 'stack': 'Error: Value is null\n    at f (http://127.0.0.1:57358/lightweight-charts.js:7:2213)\n    at An.td (http://127.0.0.1:57358/lightweight-charts.js:7:86360)\n    at Pe.setCrosshairPosition (http://127.0.0.1:57358/lightweight-charts.js:7:159252)\n    at s (http://127.0.0.1:57358/bundle.js:1:41778)\n    at Object.d [as o] (http://127.0.0.1:57358/bundle.js:1:42111)\n    at http://127.0.0.1:57358/lightweight-charts.js:7:6631\n    at Array.forEach (<anonymous>)\n    at k.m (http://127.0.0.1:57358/lightweight-charts.js:7:6617)\n    at Object.o (http://127.0.0.1:57358/lightweight-charts.js:7:157503)\n    at http://127.0.0.1:57358/lightweight-charts.js:7:6631', 'message': 'Value is null'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joach\anaconda3\envs\py310n\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\joach\anaconda3\envs\py310n\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\joach\anaconda3\envs\py310n\lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
KeyError: 'line'
